import type { ReviewItem } from "../domain/types";

export const reviewQueue: ReviewItem[] = [
  {
    rank: 1,
    rankingReasons: ["Strong specific truth", "Low cliché risk", "Broad relationship resonance"],
    concept: {
      id: "concept_domestic_ceasefire",
      title: "The Domestic Ceasefire",
      premise: "Long relationships survive on tiny treaties nobody remembers signing.",
      hook: "We don't communicate. We maintain a fragile NATO alliance about the dishwasher.",
      comicEngine: "Escalates a petty domestic disagreement into international diplomacy.",
      primaryUniverseId: "relationships",
      secondaryUniverseIds: ["marriage", "everyday-wtf"],
      targetAudienceIds: ["long-term-partners"],
      formatPlatformIds: ["text-post"],
      researchNotes: ["Prototype fixture only; not researched or approved for publication."],
      sourceRefs: [],
      status: "AWAITING_MARKIE",
      createdAt: "2026-08-31T12:00:00.000Z",
      createdBy: "GIDDY",
      schemaVersion: 1,
    },
    variants: [
      {
        id: "variant_domestic_ceasefire_a",
        conceptId: "concept_domestic_ceasefire",
        label: "NATO",
        body: "We don't communicate. We maintain a fragile NATO alliance about the dishwasher.",
        angle: "Domestic geopolitics",
        revision: 1,
        status: "SELECTED",
        createdAt: "2026-08-31T12:05:00.000Z",
      },
    ],
    score: {
      id: "score_domestic_ceasefire_a",
      conceptId: "concept_domestic_ceasefire",
      variantId: "variant_domestic_ceasefire_a",
      evaluator: "Giddy internal review",
      evaluatorVersion: "foundation-1",
      funny: 9,
      giddyVoice: 9,
      originality: 8,
      relatability: 8,
      sharePotential: 8,
      commentPotential: 7,
      humanSounding: 9,
      clichePenalty: 1,
      aiFeelingPenalty: 1,
      baseScore: 82,
      gateFailures: [],
      recommendation: "SHORTLIST",
      strongestElement: "The metaphor makes a familiar fight feel newly specific.",
      primaryWeakness: "Could skew marriage-heavy if the surrounding batch lacks breadth.",
      rationale: "A compact, human-sounding line with a clear comic engine and strong send-to-a-friend behavior.",
      createdAt: "2026-08-31T12:10:00.000Z",
    },
  },
];
